### ISSUE TITLE
Suggestion of related work

### ISSUE THREAD

**Issue by holarissun** [zjunlp/Prompt4ReasoningPapers#15]
Dear repo authors,

Thanks for building the excellent repo, it is very helpful in tracking the recent advances in the area.

I was wondering if our recent work (accepted by ICLR'2024) [Prompt-OIRL](https://arxiv.org/pdf/2309.06553.pdf) --- using inverse RL for prompt optimization in arithmetic reasoning tasks can be included in the repo.

Please find also the openreview [forum link](https://openreview.net/forum?id=N6o0ZtPzTg) of our paper.

Many thanks,
Hao

**Comment by GoooDte** [comment]
Yeah, feel free to directly commit a pr.

**Comment by holarissun** [comment]
Thanks for your prompt reply. 
Committed for your review :) 

Best wishes,
Hao
