### ISSUE TITLE
Asking for figure images

### ISSUE THREAD

**Issue by teddythinh** [zjunlp/Prompt4ReasoningPapers#17]
Dear authors,

Thank you for your excellent effort. It's really helpful to me in my research.

I was wondering if you publish your figure images from any sources. I'd need it for my report and slideshow.

Best regards,
Thinh Pham

**Comment by GoooDte** [comment]
Hello! Thanks for your attention to our work.
You can try to obtain our images on arxiv TeX source through this URL https://arxiv.org/src/2211.07504

**Comment by GoooDte** [comment]
Hello! Thanks for your attention to our work.
You can try to obtain our images through arxiv TeX Source and it's equal to this URL https://arxiv.org/src/2212.09597

**Comment by teddythinh** [comment]
@GoooDte Thank you for fast reply. I have downloaded and checked inside the `figs` folder. There is no "Figure 8: Taxonomy of Reasoning with Language Model Prompting" that presented in the paper. Can you double-check again? Thanks again!

![image](https://github.com/zjunlp/Prompt4ReasoningPapers/assets/85171754/677bd450-cab1-43be-8fcd-767a00d1a23e)

Regards,
Thinh Pham

**Comment by GoooDte** [comment]
The taxonomy figure is drawn through latex and the source code can be found in `categories_tree_small.tex` or `categories_tree_big.tex`.

**Comment by teddythinh** [comment]
Thanks for the explanation @GoooDte. I can see it now.

Best wishes to you and your research team for the future.
 
Regards,
Thinh Pham
